//------------------------------------------------------------------------------
// Author : Strix
// Github : https://github.com/KorStrix/SheetParser
//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Linq;
using UnityEngine;



public class ItemData_Container : UnityEngine.ScriptableObject
{
    
    private static ItemData_Container _instance;
    
    public List<ItemData> listData;
    
    public Dictionary<EItemType, ItemData> mapData_Key_Is_eItemType;
    
    public static ItemData_Container instance
    {
        get
        {
               return _instance;
        }
    }
    
    public static void DoInit(ItemData_Container pSingletonInstance, bool bIsUpdateChildAsset)
    {
          _instance = pSingletonInstance;
#if UNITY_EDITOR
           if(bIsUpdateChildAsset)
           {
              _instance.listData.Clear();
               Object[] arrObject = UnityEditor.AssetDatabase.LoadAllAssetRepresentationsAtPath(UnityEditor.AssetDatabase.GetAssetPath(_instance));
               for (int i = 0; i < arrObject.Length; i++)
                  _instance.listData.Add((ItemData)arrObject[i]);
               if(Application.isPlaying == false)
               {
                   UnityEditor.EditorUtility.SetDirty(_instance);
                   UnityEditor.SceneManagement.EditorSceneManager.MarkSceneDirty(UnityEditor.SceneManagement.EditorSceneManager.GetActiveScene());
               }
           }
#endif
        _instance.Init_mapData_Key_Is_eItemType();
    }
    
    private void Init_mapData_Key_Is_eItemType()
    {
        this.mapData_Key_Is_eItemType = listData.ToDictionary(x => x.eItemType);
    }
}

#region 
static
public class ItemData_ContainerHelper
{
    
    public static ItemData GetItemData(this EItemType eKey, System.Action<string> OnError = null)
    {
          ItemData pData;
          if(ItemData_Container.instance.mapData_Key_Is_eItemType.TryGetValue(eKey, out pData) == false)
          {
              if(OnError != null)
                  OnError(nameof(ItemData_Container) + "- Not Found Data // Key : " + eKey);
          }
          return pData;
    }
}
#endregion
