//------------------------------------------------------------------------------
// Author : Strix
// Github : https://github.com/KorStrix/SheetParser
//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Linq;
using UnityEngine;



public class LabNoteData_Container : UnityEngine.ScriptableObject
{
    
    private static LabNoteData_Container _instance;
    
    public List<LabNoteData> listData;
    
    public Dictionary<ESubjectType, LabNoteData> mapData_Key_Is_eSubjectType;
    
    public static LabNoteData_Container instance
    {
        get
        {
               return _instance;
        }
    }
    
    public static void DoInit(LabNoteData_Container pSingletonInstance, bool bIsUpdateChildAsset)
    {
          _instance = pSingletonInstance;
#if UNITY_EDITOR
           if(bIsUpdateChildAsset)
           {
              _instance.listData.Clear();
               Object[] arrObject = UnityEditor.AssetDatabase.LoadAllAssetRepresentationsAtPath(UnityEditor.AssetDatabase.GetAssetPath(_instance));
               for (int i = 0; i < arrObject.Length; i++)
                  _instance.listData.Add((LabNoteData)arrObject[i]);
               if(Application.isPlaying == false)
               {
                   UnityEditor.EditorUtility.SetDirty(_instance);
                   UnityEditor.SceneManagement.EditorSceneManager.MarkSceneDirty(UnityEditor.SceneManagement.EditorSceneManager.GetActiveScene());
               }
           }
#endif
        _instance.Init_mapData_Key_Is_eSubjectType();
    }
    
    private void Init_mapData_Key_Is_eSubjectType()
    {
        this.mapData_Key_Is_eSubjectType = listData.ToDictionary(x => x.eSubjectType);
    }
}

public enum ESubjectType
{
    
    SCP_096_COPY,
    
    SCP_049_COPY,
    
    SCP_035_COPY,
    
    SCP_999_COPY,
    
    NO_001,
    
    NO_002,
}

#region 
static
public class LabNoteData_ContainerHelper
{
    
    public static LabNoteData GetLabNoteData(this ESubjectType eKey, System.Action<string> OnError = null)
    {
          LabNoteData pData;
          if(LabNoteData_Container.instance.mapData_Key_Is_eSubjectType.TryGetValue(eKey, out pData) == false)
          {
              if(OnError != null)
                  OnError(nameof(LabNoteData_Container) + "- Not Found Data // Key : " + eKey);
          }
          return pData;
    }
}
#endregion
