//------------------------------------------------------------------------------
// Author : Strix
// Github : https://github.com/KorStrix/SheetParser
//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Linq;
using UnityEngine;



public class LanguageData_Container : UnityEngine.ScriptableObject
{
    
    private static LanguageData_Container _instance;
    
    public List<LanguageData> listData;
    
    public Dictionary<ELanguageKey, LanguageData> mapData_Key_Is_eLanguageKey;
    
    public static LanguageData_Container instance
    {
        get
        {
               return _instance;
        }
    }
    
    public static void DoInit(LanguageData_Container pSingletonInstance, bool bIsUpdateChildAsset)
    {
          _instance = pSingletonInstance;
#if UNITY_EDITOR
           if(bIsUpdateChildAsset)
           {
              _instance.listData.Clear();
               Object[] arrObject = UnityEditor.AssetDatabase.LoadAllAssetRepresentationsAtPath(UnityEditor.AssetDatabase.GetAssetPath(_instance));
               for (int i = 0; i < arrObject.Length; i++)
                  _instance.listData.Add((LanguageData)arrObject[i]);
               if(Application.isPlaying == false)
               {
                   UnityEditor.EditorUtility.SetDirty(_instance);
                   UnityEditor.SceneManagement.EditorSceneManager.MarkSceneDirty(UnityEditor.SceneManagement.EditorSceneManager.GetActiveScene());
               }
           }
#endif
        _instance.Init_mapData_Key_Is_eLanguageKey();
    }
    
    private void Init_mapData_Key_Is_eLanguageKey()
    {
        this.mapData_Key_Is_eLanguageKey = listData.ToDictionary(x => x.eLanguageKey);
    }
}

public enum ELanguageKey
{
    
    Player_Can_Open_Drawer,
    
    Player_Find_Key_First,
    
    Player_Colleague_GoBackHome,
    
    Cant_Open_Player_Room,
    
    Player_Can_Open_Lab_Passage,
    
    Player_Broken_Door_Script,
    
    Player_Remember_Script_0,
    
    Player_Remember_Script_1,
    
    Player_Died_Subject_Script,
    
    Player_No_Battery,
    
    Player_Find_Battery,
    
    Player_Cant_Open_Under_Lobby_Door,
    
    Player_Upper_Passage_Enter_Script,
    
    Player_Step_2_Door_Open_Script_0,
    
    Player_Step_2_Door_Open_Script_1,
    
    Player_Step_2_Door_Open_Script_2,
    
    Player_Step_2_Door_Open_Script_3,
    
    Player_Cant_Open_Step_2_Door,
    
    Player_See_SCP096_Ment_0,
    
    Player_See_SCP096_Ment_1,
    
    Player_See_SCP096_Ment_2,
    
    Player_See_SCP096_Ment_3,
    
    Player_Die_By_SCP096_Ment_0,
    
    Player_Die_By_SCP096_Ment_1,
    
    Player_Step_2_Door_Open_Script_Retry_0,
    
    Player_Step_2_Door_Open_Script_Retry_1,
    
    Player_Step_2_Door_Open_Script_Retry_2,
    
    Player_Step_2_Door_Open_Script_Retry_3,
    
    Player_Step_2_Door_Open_Script_Retry_4,
    
    Player_Step_2_Door_Open_Script_Retry_5,
    
    Player_Step_2_Door_Open_Script_Retry_6,
    
    Player_Step_2_Door_Open_Script_Retry_7,
    
    Player_Find_First_Kill_Tools_Ment,
    
    Player_Ment_None,
    
    Player_Select_Nipper_For_Kill,
    
    Player_Select_Syringe_096_For_Kill,
    
    Player_Dont_Have_Item,
    
    Player_Using_Nipper_Item,
    
    Player_Using_Syringe_096_Item,
    
    Title,
    
    OK,
    
    Yes,
    
    No,
    
    Inventory,
    
    Note,
    
    Settings,
    
    Item_Key,
    
    Item_Key_Desc,
    
    Korean,
    
    English,
    
    Sound_BGM,
    
    Sound_Effect,
    
    Language,
    
    Go_To_Main,
    
    Quit_Game,
    
    Retry_Game,
    
    Select_Kill_Tool,
    
    Lab_Note,
    
    Message,
    
    Key_First_Drawer,
    
    Hand_Light,
    
    Battery,
    
    Card_Lab_Passage,
    
    Item_Key_Step_2,
    
    Screw_Driver,
    
    Rat,
    
    Nipper,
    
    Syringe_SCP_096,
    
    Syringe_SCP_049,
    
    Syringe_SCP_035,
    
    Syringe_SCP_999,
    
    Syringe_N_001,
    
    Syringe_N_002,
    
    Lab_Note_Desc,
    
    Message_Desc,
    
    Key_First_Drawer_Desc,
    
    Hand_Light_Desc,
    
    Battery_Desc,
    
    Card_Lab_Passage_Desc,
    
    Item_Key_Step_2_Desc,
    
    Screw_Driver_Desc,
    
    Rat_Desc,
    
    Nipper_Desc,
    
    Syringe_SCP_096_Desc,
    
    Syringe_SCP_049_Desc,
    
    Syringe_SCP_035_Desc,
    
    Syringe_SCP_999_Desc,
    
    Syringe_N_001_Desc,
    
    Syringe_N_002_Desc,
    
    No_Battery,
    
    Page_Numbering,
    
    Lab_Minmap,
    
    Lab_Subject_List,
    
    Lab_Test_Log,
    
    Subject_No,
    
    Test_Room,
    
    Subject_Desc,
    
    Subject_Name_0,
    
    Subject_Name_1,
    
    Subject_Name_2,
    
    Subject_Name_3,
    
    Subject_Name_4,
    
    Subject_Name_5,
    
    Subject_Desc_0,
    
    Subject_Desc_1,
    
    Subject_Desc_2,
    
    Subject_Desc_3,
    
    Subject_Desc_4,
    
    Subject_Desc_5,
    
    Test_Log_Title,
    
    Test_Log_Date_0,
    
    Test_Log_Date_1,
    
    Test_Log_Date_2,
    
    Test_Log_Date_3,
    
    Test_Log_0,
    
    Test_Log_1,
    
    Test_Log_2,
    
    Test_Log_3,
    
    Test_Log_Interactive_0,
    
    Test_Log_Interactive_1,
    
    Test_Log_Interactive_2,
    
    Test_Log_Interactive_3,
    
    Subject_Room_0,
    
    Subject_Room_1,
    
    Subject_Room_2,
    
    Subject_Room_3,
    
    Subject_Room_4,
    
    Subject_Room_5,
    
    Room_Player_Name,
    
    Room_Colleague_Name,
    
    Room_Under_Lobby_Name,
    
    Room_Under_Passage_Name,
    
    Room_Storage_Name,
    
    Room_Upper_Passage_Name,
    
    Room_Step_2_Name,
    
    Room_Player_Desc,
    
    Room_Colleague_Desc,
    
    Room_Under_Lobby_Desc,
    
    Room_Under_Passage_Desc,
    
    Room_Storage_Desc,
    
    Room_Upper_Passage_Desc,
    
    Room_Step_2_Desc,
    
    Memo_From_Colleague,
    
    Opening_Action_Script_0,
    
    Opening_Action_Script_1,
    
    Opening_Action_Script_2,
    
    Opening_Action_Script_3,
    
    Opening_Action_Script_4,
    
    Opening_Action_Script_5,
    
    Opening_Action_Script_6,
    
    Opening_Action_Script_7,
    
    Opening_Action_Script_8,
    
    Opening_Action_Script_9,
    
    Opening_Action_Script_10,
    
    Opening_Action_Script_11,
    
    Find_Lab_Note,
    
    Can_Get_Item_By_NoLight,
    
    Get_Lab_Note,
    
    Touch_Bag_Icon,
    
    You_Died,
    
    System_Input_Your_ID,
    
    System_Check_Your_PW,
    
    System_Get_Item,
    
    System_Please_Find_Lab_Note,
    
    System_Dont_Have_Item,
}

#region 
static
public class LanguageData_ContainerHelper
{
    
    public static LanguageData GetLanguageData(this ELanguageKey eKey, System.Action<string> OnError = null)
    {
          LanguageData pData;
          if(LanguageData_Container.instance.mapData_Key_Is_eLanguageKey.TryGetValue(eKey, out pData) == false)
          {
              if(OnError != null)
                  OnError(nameof(LanguageData_Container) + "- Not Found Data // Key : " + eKey);
          }
          return pData;
    }
}
#endregion
