//------------------------------------------------------------------------------
// Author : Strix
// Github : https://github.com/KorStrix/SheetParser
//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Linq;
using UnityEngine;



public enum EConfirmType
{
    
    /// <summary>
    /// 확인 버튼만 있을 때
    /// </summary>
    Confirm_OK,
    
    /// <summary>
    /// 예, 아니오 버튼이 있을 때
    /// </summary>
    Confirm_YES_NO,
}

public enum EItemType
{
    
    NONE = -1,
    
    /// <summary>
    /// 연구 노트
    /// </summary>
    Item_Lab_Note,
    
    /// <summary>
    /// 동료방 두번째 서랍 열쇠
    /// </summary>
    Item_Key_First_Drawer,
    
    /// <summary>
    /// 손전등
    /// </summary>
    Item_Hand_Light,
    
    /// <summary>
    /// 건전지
    /// </summary>
    Item_Battery,
    
    /// <summary>
    /// 연구실 가는 복도 키
    /// </summary>
    Item_Card_Lab_Passage,
    
    /// <summary>
    /// 2단계 문 열쇠
    /// </summary>
    Item_Key_Step_2,
    
    /// <summary>
    /// 십자 드라이버 아이템
    /// </summary>
    Item_Screw_Driver,
    
    /// <summary>
    /// 죽은 실험용 쥐
    /// </summary>
    Item_Rat,
    
    /// <summary>
    /// 니퍼
    /// </summary>
    Item_Nipper,
    
    /// <summary>
    /// SCP 096 사살용 주사기
    /// </summary>
    Item_Syringe_SCP_096,
    
    /// <summary>
    /// SCP 049 사살용 주사기
    /// </summary>
    Item_Syringe_SCP_049,
    
    /// <summary>
    /// SCP 035 사살용 주사기
    /// </summary>
    Item_Syringe_SCP_035,
    
    /// <summary>
    /// SCP 999 사살용 주사기
    /// </summary>
    Item_Syringe_SCP_999,
    
    /// <summary>
    /// N 001 사살용 주사기
    /// </summary>
    Item_Syringe_N_001,
    
    /// <summary>
    /// N 002 사살용 주사기
    /// </summary>
    Item_Syringe_N_002,
    
    /// <summary>
    /// 총 아이템 개수
    /// </summary>
    Item_Max,
}

public enum EInteractiveObjType
{
    
    NONE = -1,
    
    /// <summary>
    /// 문이 열리는 캐비닛
    /// </summary>
    OBJ_Cabinet,
    
    /// <summary>
    /// 열리는 서랍장
    /// </summary>
    OBJ_Drawer,
    
    /// <summary>
    /// 터치하면 비밀번호 입력창이 뜬다
    /// </summary>
    OBJ_Password_Pad,
    
    /// <summary>
    /// 터치하면 내용을 볼 수 있는 확대 팝업창이 뜬다.
    /// </summary>
    OBJ_Show_Detail,
    
    /// <summary>
    /// 문 : 경우에 따라서 System Message가 뜰 수도 있다.
    /// </summary>
    OBJ_Door,
    
    /// <summary>
    /// 폭파 스위치
    /// </summary>
    OBJ_Bomb_Lever,
    
    /// <summary>
    /// 터치시 플레이어가 대사를 친다.
    /// </summary>
    OBJ_Show_Player_Ment,
}

public enum EDoorType
{
    
    NONE = -1,
    
    /// <summary>
    /// 플레이어 방에 있는 문
    /// </summary>
    Door_Player_Room,
    
    /// <summary>
    /// 지하로비에 있는 문
    /// </summary>
    Door_Under_Lobby,
    
    /// <summary>
    /// 탕비실에 있는 문
    /// </summary>
    Door_Storage,
    
    /// <summary>
    /// 탕비실에 있는 냉장고문
    /// </summary>
    Door_Storage_Refrigerator,
    
    /// <summary>
    /// 2단계 방 들어가는 문
    /// </summary>
    Door_Step_2,
}

public enum EDrawerState
{
    
    NONE = -1,
    
    /// <summary>
    /// 서랍이 열려있는 상태
    /// </summary>
    Open,
    
    /// <summary>
    /// 서랍이 닫혀있는 상태
    /// </summary>
    Close,
}

public enum EDrawerType
{
    
    NONE = -1,
    
    /// <summary>
    /// 동료방 첫번째 서랍
    /// </summary>
    Colleague_First_Drawer,
}

public enum EShowPlayerMentType
{
    
    NONE = -1,
    
    /// <summary>
    /// Remeber 라고 적힌 혈흔
    /// </summary>
    Blood_Remember,
    
    /// <summary>
    /// 지하 로비에 있는 죽은 실험체
    /// </summary>
    Died_Subject,
}
