//------------------------------------------------------------------------------
// Author : Strix
// Github : https://github.com/KorStrix/SheetParser
//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Linq;
using UnityEngine;



public class RoomData_Container : UnityEngine.ScriptableObject
{
    
    private static RoomData_Container _instance;
    
    public List<RoomData> listData;
    
    public Dictionary<ERoomType, RoomData> mapData_Key_Is_eRoomType;
    
    public static RoomData_Container instance
    {
        get
        {
               return _instance;
        }
    }
    
    public static void DoInit(RoomData_Container pSingletonInstance, bool bIsUpdateChildAsset)
    {
          _instance = pSingletonInstance;
#if UNITY_EDITOR
           if(bIsUpdateChildAsset)
           {
              _instance.listData.Clear();
               Object[] arrObject = UnityEditor.AssetDatabase.LoadAllAssetRepresentationsAtPath(UnityEditor.AssetDatabase.GetAssetPath(_instance));
               for (int i = 0; i < arrObject.Length; i++)
                  _instance.listData.Add((RoomData)arrObject[i]);
               if(Application.isPlaying == false)
               {
                   UnityEditor.EditorUtility.SetDirty(_instance);
                   UnityEditor.SceneManagement.EditorSceneManager.MarkSceneDirty(UnityEditor.SceneManagement.EditorSceneManager.GetActiveScene());
               }
           }
#endif
        _instance.Init_mapData_Key_Is_eRoomType();
    }
    
    private void Init_mapData_Key_Is_eRoomType()
    {
        this.mapData_Key_Is_eRoomType = listData.ToDictionary(x => x.eRoomType);
    }
}

public enum ERoomType
{
    
    NONE,
    
    Room_Player,
    
    Room_Colleague,
    
    Room_Under_Lobby,
    
    Room_Under_Passage,
    
    Room_Storage,
    
    Room_Upper_Passage,
    
    Room_Step_2,
}

#region 
static
public class RoomData_ContainerHelper
{
    
    public static RoomData GetRoomData(this ERoomType eKey, System.Action<string> OnError = null)
    {
          RoomData pData;
          if(RoomData_Container.instance.mapData_Key_Is_eRoomType.TryGetValue(eKey, out pData) == false)
          {
              if(OnError != null)
                  OnError(nameof(RoomData_Container) + "- Not Found Data // Key : " + eKey);
          }
          return pData;
    }
}
#endregion
