//------------------------------------------------------------------------------
// Author : Strix
// Github : https://github.com/KorStrix/SheetParser
//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Linq;
using UnityEngine;



public class SoundData_Container : UnityEngine.ScriptableObject
{
    
    private static SoundData_Container _instance;
    
    public List<SoundData> listData;
    
    public Dictionary<string, SoundData> mapData_Key_Is_strSoundName;
    
    public Dictionary<ESoundKey, SoundData> mapData_Key_Is_eSoundKey;
    
    public static SoundData_Container instance
    {
        get
        {
               return _instance;
        }
    }
    
    public static void DoInit(SoundData_Container pSingletonInstance, bool bIsUpdateChildAsset)
    {
          _instance = pSingletonInstance;
#if UNITY_EDITOR
           if(bIsUpdateChildAsset)
           {
              _instance.listData.Clear();
               Object[] arrObject = UnityEditor.AssetDatabase.LoadAllAssetRepresentationsAtPath(UnityEditor.AssetDatabase.GetAssetPath(_instance));
               for (int i = 0; i < arrObject.Length; i++)
                  _instance.listData.Add((SoundData)arrObject[i]);
               if(Application.isPlaying == false)
               {
                   UnityEditor.EditorUtility.SetDirty(_instance);
                   UnityEditor.SceneManagement.EditorSceneManager.MarkSceneDirty(UnityEditor.SceneManagement.EditorSceneManager.GetActiveScene());
               }
           }
#endif
        _instance.Init_mapData_Key_Is_strSoundName();
        _instance.Init_mapData_Key_Is_eSoundKey();
    }
    
    private void Init_mapData_Key_Is_strSoundName()
    {
        this.mapData_Key_Is_strSoundName = listData.ToDictionary(x => x.strSoundName);
    }
    
    private void Init_mapData_Key_Is_eSoundKey()
    {
        this.mapData_Key_Is_eSoundKey = listData.ToDictionary(x => x.eSoundKey);
    }
}

public enum ESoundKey
{
    
    Main_BGM,
    
    UI_BagOpen,
    
    UI_Button,
    
    UI_HandLight_Switch_On,
    
    Effect_Stage2_Kill_By_BadTool,
    
    Effect_Cabinet_Door,
    
    Effect_Door,
    
    Effect_GetItem,
    
    Effect_GetKey,
    
    Effect_Keypad,
    
    Effect_Paper,
    
    Effect_Wordlock_Wheel,
    
    Effect_GetMouse,
    
    Effect_Stage1_Cardkey,
    
    Effect_Stage2_Inject,
    
    Effect_FootStep01,
    
    Effect_FootStep02,
    
    Effect_SCP_096_Scream,
    
    Effect_Metal_Door_Open,
    
    Effect_Metal_Door_Close,
}

#region 
static
public class SoundData_ContainerHelper
{
    
    public static SoundData GetSoundData(this string eKey, System.Action<string> OnError = null)
    {
          SoundData pData;
          if(SoundData_Container.instance.mapData_Key_Is_strSoundName.TryGetValue(eKey, out pData) == false)
          {
              if(OnError != null)
                  OnError(nameof(SoundData_Container) + "- Not Found Data // Key : " + eKey);
          }
          return pData;
    }
    
    public static SoundData GetSoundData(this ESoundKey eKey, System.Action<string> OnError = null)
    {
          SoundData pData;
          if(SoundData_Container.instance.mapData_Key_Is_eSoundKey.TryGetValue(eKey, out pData) == false)
          {
              if(OnError != null)
                  OnError(nameof(SoundData_Container) + "- Not Found Data // Key : " + eKey);
          }
          return pData;
    }
}
#endregion
